# Which localisation file should the plugin use
localisation: "ua"

# Set the radius of local chat.
radius: 200

# If the player should pay to use global chat
global-pay:
  item:
    enabled: false
    material: "REDSTONE"
    nbt: "GLOBAL"

# Both fully support PlaceholderAPI
# Global chat format
global-format: "&8[&cG&8]&r &6%player% &e>&r %message%"

# Local chat format
local-format: "&8[&aL&8]&r &6%player% &e>&r %message%"

# Private message format
private-format-to: "&8[&bПП&8]&r &6%player% &e> Ви: &r%message%"
private-format-from: "&8[&bПП&8]&r Ви &e> &6%player%&r: %message%"

mentions:
  enabled: true
  highlight:
    enabled: true
    format: "&e%player%&r"
  sound:
    enabled: true
    name: "block.note_block.pling"
    volume: 0.5
    pitch: 2.0
  actionbar:
    enabled: true

# Message on player join/leave
join: false
quit: false